DROP TABLE KSIAZKI CASCADE CONSTRAINTS;
DROP TABLE CZYTELNICY CASCADE CONSTRAINTS;
DROP TABLE HISTORIA_WYP CASCADE CONSTRAINTS;
DROP TABLE AUTORZY CASCADE CONSTRAINTS;
DROP TABLE WYDAWNICTWA CASCADE CONSTRAINTS;
DROP TABLE DZIALY CASCADE CONSTRAINTS;

CREATE TABLE KSIAZKI
  (
    ID_KSIAZKI      NUMBER (4) NOT NULL,
    ISBN            NUMBER (13),
    TYTUL           VARCHAR2 (50 BYTE) NOT NULL,
    ID_AUTORA       NUMBER (4) NOT NULL,
    ID_WYDAWNICTWA  NUMBER (4) NOT NULL,
    ID_DZIALU       NUMBER (4) NOT NULL,
    WYPOZYCZONA     NUMBER (1) NOT NULL
  ) ;
ALTER TABLE KSIAZKI ADD CONSTRAINT KSIAZKI_PK PRIMARY KEY (ID_KSIAZKI);

CREATE TABLE CZYTELNICY
  (
    ID_CZYTELNIKA       NUMBER (4) NOT NULL ,
    IMIE                VARCHAR2 (50 BYTE) NOT NULL, 
    NAZWISKO            VARCHAR2 (50 BYTE) NOT NULL,
    PESEL               VARCHAR2 (11 BYTE) NOT NULL, 
    TELEFON             NUMBER (9) NOT NULL,
    DATA_ZAL_KONTA      DATE NOT NULL,
    LICZBA_WYP_KSIAZEK  NUMBER (4),
    BLOKADA             NUMBER (1) NOT NULL
  ) ;
ALTER TABLE CZYTELNICY ADD CONSTRAINT CZYTELNICY_PK PRIMARY KEY (ID_CZYTELNIKA);


CREATE TABLE HISTORIA_WYP
  (
    ID_KSIAZKI              NUMBER (4) NOT NULL,
    ID_CZYTELNIKA           NUMBER (4) NOT NULL,
    DATA_WYP                DATE NOT NULL,
    PLAN_DATA_ZWROTU        DATE NOT NULL, 
    DATA_ZWROTU             DATE,
    PRZETRZYMANA            NUMBER (1) NOT NULL 
  ) ;

CREATE TABLE AUTORZY
  (
    ID_AUTORA   NUMBER (4) NOT NULL,
    IMIE	VARCHAR2 (50 BYTE) NOT NULL,
    NAZWISKO    VARCHAR2 (50 BYTE) NOT NULL
  ) ;
ALTER TABLE AUTORZY ADD CONSTRAINT AUTORZY_PK PRIMARY KEY (ID_AUTORA);

CREATE TABLE WYDAWNICTWA
  (
    ID_WYDAWNICTWA  NUMBER (4) NOT NULL,
    NAZWA           VARCHAR2 (50 BYTE) NOT NULL
  ) ;
ALTER TABLE WYDAWNICTWA ADD CONSTRAINT WYDAWNICTWA_PK PRIMARY KEY (ID_WYDAWNICTWA);

CREATE TABLE DZIALY
  (
    ID_DZIALU   NUMBER (4) NOT NULL,
    NAZWA       VARCHAR2 (50 BYTE) NOT NULL,
    REG_POCZ    NUMBER (4) NOT NULL,
    REG_KON     NUMBER (4) NOT NULL
  ) ;
ALTER TABLE DZIALY ADD CONSTRAINT DZIALY_PK PRIMARY KEY (ID_DZIALU);

ALTER TABLE ksiazki ADD CONSTRAINT Ksiazki_Autorzy_FK FOREIGN KEY ( ID_AUTORA ) REFERENCES Autorzy ( ID_Autora ) ;

ALTER TABLE Ksiazki ADD CONSTRAINT Ksiazki_Wydaw_FK FOREIGN KEY ( ID_wydawnictwa ) REFERENCES Wydawnictwa ( ID_wydawnictwa ) ;

ALTER TABLE Ksiazki ADD CONSTRAINT Ksiazki_Dzialy_FK FOREIGN KEY ( ID_dzialu ) REFERENCES Dzialy ( ID_dzialu ) ;

ALTER TABLE historia_wyp ADD CONSTRAINT HW_Ksiazki_FK FOREIGN KEY ( ID_ksiazki ) REFERENCES ksiazki ( ID_ksiazki ) ;

ALTER TABLE historia_wyp ADD CONSTRAINT HW_Czytenicy_FK FOREIGN KEY ( ID_czytelnika ) REFERENCES czytelnicy ( ID_czytelnika ) ;

